### ISSUE TITLE
Defaults for LaTeX and MathML fields

### ISSUE THREAD

**Issue by physikerwelt** [ag-gipp/vmext-demo#12]
It would be nice if a user goes the demo page the fields have meaningful defaults.
My suggestion
`$\EulerGamma@{z}=\Int{0}{\infty}@{t}{e^{-t}t^{z-1}}$`
and the exactly same expresion with another bound variable
`$\EulerGamma@{z}=\Int{0}{\infty}@{x}{e^{-x}t^{z-1}}$`
and the respective values for the mathml and identical simlarity scores.
Also if possible I would show the render AST on the left when you visit the page without having to press any button.
@nmeuschke  what do you think?

**Comment by vstange** [comment]
Show the AST renderer on the left? Just to clarify, you mean the Merged AST on the right preloaded?

**Comment by physikerwelt** [comment]
No the rendering of the first formula.

**Comment by physikerwelt** [comment]
So yes. I mean right rather than left.

**Comment by vstange** [comment]
Okay, got it :)

**Comment by vstange** [comment]
New default example is online.
