### ISSUE TITLE
rename build artifact

### ISSUE THREAD

**Issue by physikerwelt** [ag-gipp/vmext-demo#14]
The name mathpipeline is confusing since there is [mathpipe](https://github.com/physikerwelt/mathpipe)

**Comment by vstange** [comment]
The change to "vmext-demo" should do fine?

**Comment by physikerwelt** [comment]
yes

**Comment by physikerwelt** [comment]
I'm not sure about the dash though. maybe we can go for simvis?

**Comment by vstange** [comment]
what is the vis for?

**Comment by physikerwelt** [comment]
visualization but other proposal are welcome as well

**Comment by physikerwelt** [comment]
This is almost done.  https://github.com/ag-gipp/vmext-demo/search?utf8=%E2%9C%93&q=mathpipeline&type=
- [ ]  rename the jar file
- [ ] restart the server

It might make sense to do that before you deploy https://github.com/ag-gipp/vmext-demo/pull/20 to drmf-beta

**Comment by physikerwelt** [comment]
@AndreG-P any progress here?

**Comment by AndreG-P** [comment]
Well, there is a new version of the visualization developed by Moritz. The only reason we have vmext-demo online are the endpoints. According to this, I think we should rename the artifact again to reflect this.
