### ISSUE TITLE
Randomly trouble with ast-renderer

### ISSUE THREAD

**Issue by AndreG-P** [ag-gipp/vmext-demo#18]
@vstange I just recognized some trouble with the AST-renderer in vmext-demo. It does not appear anymore. The script http://math.citeplag.org/widgets/formula-ast-widget.js seems be broken.
I just remember you wanted to redirect something from citeplag to another location. Could that be the reason?

**Comment by AndreG-P** [comment]
Yes, that was the problem. Change the link of mast to https://vmext.wmflabs.org/ solves the issue. e5a989d0fd7eb22343f1822059a9a7509b642a87

**Comment by vstange** [comment]
Thanks, totally forgot that the vmext demo still has this link.
